## Generated by tools/fluentize.py from literal chrome strings.
ingame-player-aircraft-tooltip = Aircraft
ingame-player-building-tooltip = Buildings
ingame-player-feedback-tooltip = Capture feedback
ingame-player-debug-button-tooltip = Debug Menu
ingame-player-force-attack-tooltip = Force Attack
ingame-player-force-move-tooltip = Force Move
ingame-player-infantry-tooltip = Infantry
ingame-player-naval-tooltip = Naval
ingame-player-beacon-button-tooltip = Place Beacon
ingame-player-repair-button-tooltip = Repair
ingame-player-feedback-tooltip-desc = Save a fog-respecting screenshot and live game state, then open the local feedback form.
ingame-player-force-attack-tooltip-desc =
    Selected units will attack the targeted unit or location
    ignoring their default activity for the target.

    Left-click icon then right-click on target.
    Hold <(Ctrl)> to activate temporarily while commanding units.
ingame-player-guard-tooltip-desc =
    Selected units will follow the targeted unit.

    Left-click icon then right-click on target unit.
ingame-player-force-move-tooltip-desc =
    Selected units will move to the desired location
     - Default activity for the target is suppressed
     - Vehicles will attempt to crush enemies at the target location

    Left-click icon then right-click on target.
    Hold <(Alt)> to activate temporarily while commanding units.
ingame-player-attack-move-tooltip-desc =
    Selected units will move to the desired location
    and attack any enemies they encounter en route.

    Hold <(Ctrl)> while targeting to order an Assault Move
    that attacks any units or structures encountered en route.

    Left-click icon then right-click on target location.
ingame-player-deploy-tooltip-desc =
    Selected units will perform their default deploy activity
     - MCVs will unpack into a Construction Yard
     - Construction Yards will re-pack into a MCV
     - Transports will unload their passengers
     - Demolition Trucks and MAD Tanks will self-destruct
     - Aircraft will return to base

    Acts immediately on selected units.
ingame-player-stop-tooltip-desc =
    Selected units will stop their current activity.
    Selected buildings will reset their rally point.

    Acts immediately on selected targets.
ingame-player-scatter-tooltip-desc =
    Selected units will stop their current activity
    and move to a nearby location.

    Acts immediately on selected units.
ingame-player-sell-button-tooltip = Sell
ingame-player-support-tooltip = Support
ingame-player-queue-orders-tooltip-desc =
    Use Waypoint Mode to give multiple linking commands
    to the selected units. Units will execute the commands
    immediately upon receiving them.

    Left-click icon then give commands in the game world.
    Hold <(Shift)> to activate temporarily while commanding units.
ingame-player-vehicle-tooltip = Vehicles
ingame-observer-harvesters-header-text = Harvesters
ingame-observer-options-button-text = Options (Esc)
ingame-debug-title-text = Debug Options
ingame-debug-show-depth-preview-text = Show Depth Data
mainmenu-prerelease-notification-prompt-text-b-text = for the community to follow development and as example for modders.
mainmenu-prerelease-notification-continue-button-text = I Understand
mainmenu-prerelease-notification-prompt-text-c-text = Many features are missing or incomplete, performance has not been
mainmenu-prerelease-notification-prompt-text-d-text = optimized, and balance will not be addressed until a future beta.
mainmenu-prerelease-notification-prompt-title-text = { -product-name } developer preview
mainmenu-prerelease-notification-prompt-text-a-text = This pre-alpha build of { -product-name } is made available
hotkey-description-production-type-building = Building Tab
hotkey-description-production-type-defense = Defense Tab
hotkey-description-production-type-infantry = Infantry Tab
hotkey-description-production-type-vehicle = Vehicle Tab
hotkey-description-production-type-aircraft = Aircraft Tab
hotkey-description-production-type-naval = Naval Tab
loadscreen-loading = Carving wooden nickels..., Preparing paratroopers..., Welcoming you to Texas..., Optimizing helium mix..., Receiving thoughts..., Igniting boosters...
support-power-timer = { $player }'s { $support-power }: { $time }
