# GENERATED by tools/standalone-names.py: neutral names for the standalone game. Overrides the shared
# messages that use a Red Alert 2 coined name (the classic add-on keeps them). Do not edit by hand.

## from languages/rules/en.ftl
actor-gaairc-name = Airfield

## from languages/rules/en.ftl
actor-amradr-name = American Airfield

## from languages/rules/en.ftl
actor-gaweap-name = Vehicle Factory

## from languages/rules/en.ftl
actor-gadept-description = Repairs vehicles (for a price).

## from languages/rules/en.ftl
actor-gatech-name = Tech Center

## from languages/rules/en.ftl
actor-gawall-name = Wall

## from languages/rules/en.ftl
actor-napowr-name = Power Plant

## from languages/rules/en.ftl
actor-naweap-name = Vehicle Factory

## from languages/rules/en.ftl
actor-nadept-description = Repairs vehicles (for a price).

## from languages/rules/en.ftl
actor-natech-name = Tech Center

## from languages/rules/en.ftl
actor-nawall-name = Wall

## from languages/rules/en.ftl
actor-cmin-name = Ore Harvester

## from languages/rules/en.ftl
actor-harv-name = Armed Harvester

## from languages/rules/en.ftl
actor-htk-name = AA Carrier

## from modern-factions/iran-messages.ftl
ra2-r2toufan-description = Rocket gunship vs infantry and light vehicles.
    Weak vs heavy tanks; vulnerable to dedicated AA.
    Produced at the Vehicle Factory.

## from modern-factions/iran-messages.ftl
ra2-r2azar-description = Fast strafing strikes vs armor and buildings.
    Long reload between passes. Weak vs interceptors and AA.
    Produced at the Vehicle Factory; no airfield required.

## from modern-factions/turkey-messages.ftl
ra2-r2sahin-description = Fast air-superiority fighter. Four missiles; automatically
    returns to the Airfield to rearm.
    Cannot attack ground targets. Requires Tech Center.

## from modern-factions/saudi-messages.ftl
ra2-r2f15sa-description = Multirole fighter: four air-to-air missiles and two guided
    strike missiles; returns to the Airfield to rearm.
    Requires Tech Center.

## from modern-factions/saudi-messages.ftl
ra2-r2ah64sa-description = Attack helicopter with a chain gun and anti-armor rockets.
    Rockets hit laser-marked targets harder. Vulnerable to anti-air.
    Requires Tech Center.
