#!/usr/bin/env python3
"""Generate mods/rtsai-classic/mod.yaml from the standalone manifest (mods/rtsai/mod.yaml).

The classic add-on is the standalone game plus the original Red Alert 2 factions, maps, tilesets, music and cursors,
played with the player's own RA2 files (installed by mods/rtsai-content). Deriving its manifest from the standalone
one keeps the two in step: every shared rules, sequence, weapon, voice, chrome and text file is listed once, in
mods/rtsai/mod.yaml. Standalone-only entries (anything under ra2|standalone/) are dropped, and the classic-only
sections below are swapped in.

  python tools/build-classic-manifest.py           # write mods/rtsai-classic/mod.yaml
  python tools/build-classic-manifest.py --check   # exit 1 if it is out of date (tools/standalone-check runs this)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "mods" / "rtsai" / "mod.yaml"
DST = ROOT / "mods" / "rtsai-classic" / "mod.yaml"

HEADER = """# GENERATED by tools/build-classic-manifest.py from mods/rtsai/mod.yaml. Do not edit; edit the standalone manifest
# (shared files) or the CLASSIC sections in the generator, then rerun it. make test fails when this is stale.
#
# RTS AI Classic: the optional add-on with the original Red Alert 2 factions and maps. It needs the player's own RA2
# files, which mods/rtsai-content imports on first launch. No EA file ships with it.
"""

CLASSIC = {
    "Metadata": """Metadata:
	Title: classic-mod-title
	WindowTitle: classic-window-title
	Version: {DEV_VERSION}
""",
    "PackageFormats": "PackageFormats: Mix, AudioBag\n",
    "FileSystem": """FileSystem: ContentInstallerFileSystem
	SystemPackages:
		^EngineDir
		$rtsai: ra2
		$rtsai-classic: classic
		^EngineDir|mods/common: common
		~^SupportDir|Content/ra2: content
		ra2|uibits
	ContentPackages:
		# Red Alert 2 (the player's own files, installed by rtsai-content)
		content|language.mix: lang
		content|ra2.mix: ra2mix
		~content|theme.mix
		lang|cameo.mix: cameo
		~lang|audio.mix: audio
		~audio|audio.bag
		~lang|audio.bag
		ra2mix|cache.mix: cache
		ra2mix|conquer.mix: conquer
		ra2mix|generic.mix
		ra2mix|isogen.mix
		ra2mix|isosnow.mix
		ra2mix|isotemp.mix
		ra2mix|isourb.mix
		ra2mix|load.mix
		ra2mix|local.mix: local
		ra2mix|neutral.mix
		ra2mix|sidec01.mix
		ra2mix|sidec02.mix
		ra2mix|sno.mix
		ra2mix|snow.mix
		ra2mix|tem.mix
		ra2mix|temperat.mix
		ra2mix|urb.mix
		ra2mix|urban.mix
		# Mod-provided packages load after content so they can override it.
		ra2|bits
		ra2|bits/cameos
	ContentInstallerMod: rtsai-content
""",
    "MapFolders": """MapFolders:
	classic|maps: System
	ra2|maps: System
	~^SupportDir|maps/rtsai-classic/{DEV_VERSION}: User
""",
    "Cursors": "Cursors:\n\tclassic|cursors.yaml\n",
    "TileSets": """TileSets:
	classic|tilesets/temperat.yaml
	classic|tilesets/snow.yaml
	classic|tilesets/urban.yaml
""",
    "Music": "Music:\n\tclassic|audio/music.yaml\n",
}
APPEND = {
    "Rules": ["classic|rules/factions.yaml"],
    "FluentMessages": ["classic|languages/en.ftl"],
}


def sections(text: str) -> list[tuple[str, str]]:
    """Top-level manifest sections in order: (key, full text including trailing blank lines)."""
    out, cur, key = [], [], None
    for line in text.splitlines(keepends=True):
        m = re.match(r"^([A-Za-z][A-Za-z0-9]*):", line)
        if m:
            if cur:
                out.append((key, "".join(cur)))
            key, cur = m[1], [line]
        elif line.startswith("#") and key is None:
            continue
        else:
            cur.append(line)
    if cur:
        out.append((key, "".join(cur)))
    return out


def build() -> str:
    text = SRC.read_text(encoding="utf-8").replace("\r\n", "\n")
    parts = []
    for key, body in sections(text):
        body = re.sub(r"(?m)^# Standalone:.*\n(^#.*\n)*", "", body)   # the standalone filesystem comment
        if key == "FileSystem":   # the standalone manifest registers no archive formats; the add-on needs MIX/BAG
            parts.append(CLASSIC["PackageFormats"] + "\n")
        if key in CLASSIC:
            tail = "\n" * (len(body) - len(body.rstrip("\n")) - 1)
            parts.append(CLASSIC[key] + tail)
            continue
        lines = [ln for ln in body.splitlines(keepends=True) if not re.match(r"^\t~?ra2\|standalone/", ln)]
        if key == "ModCredits":
            lines = [re.sub(r"ModTabTitle: ([^#\n]*?)\s*(#.*)?$", r"ModTabTitle: \1 Classic", ln) for ln in lines]
        if key in APPEND:
            items = [ln for ln in lines[1:] if ln.strip()]
            blanks = len(lines) - 1 - len(items)
            lines = [lines[0]] + items + [f"\t{x}\n" for x in APPEND[key]] + ["\n"] * blanks
        parts.append("".join(lines))
    return HEADER + "\n" + "".join(parts)


def main():
    out = build()
    if "--check" in sys.argv:
        current = DST.read_text(encoding="utf-8").replace("\r\n", "\n") if DST.exists() else ""
        if current != out:
            print(f"{DST.relative_to(ROOT)} is out of date: run python tools/build-classic-manifest.py")
            sys.exit(1)
        print(f"{DST.relative_to(ROOT)} is up to date")
        return
    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(out, encoding="utf-8", newline="\n")
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
