#!/usr/bin/env python3
"""Generate the faction loading-screen tips from the shared faction catalog.

Each faction's approved `flavour.loading` lines in OpenRA-AI/catalog/factions.json (one in its own voice, one
from a named rival) become one multi-line Fluent message, `loadscreen-faction-tips`, which RTSAILoadScreen shows
under the logo. The catalog is the single source: never edit the generated file by hand; rerun this instead.

    python tools/faction-loading-tips.py            # write mods/rtsai/modern-factions/loading-tips.ftl
    python tools/faction-loading-tips.py --check    # exit 1 if the file is out of date with the catalog
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

MOD = Path(__file__).resolve().parents[1]
CATALOG = MOD.parent / "OpenRA-AI" / "catalog" / "factions.json"
OUTPUT = MOD / "mods" / "rtsai" / "modern-factions" / "loading-tips.ftl"
MESSAGE = "loadscreen-faction-tips"
PROFILE = "ra2-modern"


def tips(catalog: dict) -> list[str]:
    factions = {faction["id"]: faction for faction in catalog["factions"]}
    names = {faction_id: faction["variants"]["ra2"]["name"] for faction_id, faction in factions.items()}
    profile = next(profile for profile in catalog["profiles"] if profile["id"] == PROFILE)
    lines = []
    for faction_id in profile["factionIds"]:
        loading = {line["perspective"]: line for line in factions[faction_id]["flavour"]["loading"]}
        lines.append(f"{names[faction_id]}: {loading['self']['text']}")
        lines.append(f"{names[loading['rival']['rival']]} on {names[faction_id]}: \"{loading['rival']['text']}\"")
    for line in lines:
        # Fluent placeables and line-leading syntax characters would change the meaning of a multi-line value.
        if re.search(r"[{}\n]", line) or line[0] in "[*.}":
            raise ValueError(f"Tip cannot be written as Fluent text: {line}")
    return lines


def render(source: bytes) -> str:
    catalog = json.loads(source.decode("utf-8"))
    digest = hashlib.sha256(source.replace(b"\r\n", b"\n")).hexdigest()
    header = [
        "## Generated by tools/faction-loading-tips.py from OpenRA-AI/catalog/factions.json. Do not edit by hand.",
        f"## Catalog revision {catalog['revision']}, sha256 {digest[:12]}. One tip per line, shown by RTSAILoadScreen.",
        "## In-world perspectives in a fictional game conflict (see the catalog's narrative.framing).",
        "",
        f"{MESSAGE} =",
    ]
    return "\n".join(header + [f"    {line}" for line in tips(catalog)]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--catalog", type=Path, default=CATALOG, help="OpenRA-AI faction catalog (default: sibling checkout)")
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale instead of writing it")
    args = parser.parse_args()
    expected = render(args.catalog.read_bytes())
    current = OUTPUT.read_bytes().decode("utf-8").replace("\r\n", "\n") if OUTPUT.exists() else None
    if args.check:
        if current != expected:
            print(f"{OUTPUT.relative_to(MOD)} is stale; run python tools/faction-loading-tips.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(MOD)} matches the catalog")
        return 0
    OUTPUT.write_bytes(expected.encode("utf-8"))
    print(f"Wrote {OUTPUT.relative_to(MOD)} ({expected.count(chr(10)) - 5} tips)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
