#!/usr/bin/env python3
"""Wire the Phase 3 base kit (mods/rtsai/standalone/base, by the art agent) into the standalone game's rules.

Writes mods/rtsai/standalone/base-kit.yaml, a standalone-only rules overlay (the classic add-on keeps the original
buildings with the player's own RA2 files):
  - the kit palette (kitbase.pal) and its player-colour remap;
  - each of the 22 stock buildings the modern factions use renders its kit role, painted per faction;
  - render traits that name sequences the kit does not have are swapped or removed, as agreed with the art agent
    (construction yard crane = full-body "build" animation, no air-factory roof, no airfield "idle-mid");
  - the Soviet-side power plant, barracks, service depot and tech centre take the Allied footprints the kit is
    drawn for (Building, HitShape, exits and rally point copied from the Allied counterparts);
  - the 8 stock buildings the kit does not replace leave the modern rosters (owner decision, 7 October 2026);
  - the two superweapon slots get standalone names (standalone/standalone.ftl).

usage: python tools/standalone-kit-rules.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "mods" / "rtsai" / "standalone" / "base-kit.yaml"
FACTIONS = ["china", "iran", "turkey", "saudi", "israel", "yemen", "hezbollah"]

ROLE = {
    "gacnst": "cnst", "nacnst": "cnst", "gapowr": "powr", "napowr": "powr", "garefn": "refn", "narefn": "refn",
    "gapile": "barr", "nahand": "barr", "gaweap": "weap", "naweap": "weap", "naradr": "radr", "gaairc": "airf",
    "gayard": "yard", "nayard": "yard", "gadept": "dept", "nadept": "dept", "gatech": "tech", "natech": "tech",
    "gacsph": "sw1", "nairon": "sw2", "gawall": "wall", "nawall": "wall",
}

# Render traits to adjust per actor (raw MiniYaml, tab-indented under the actor).
EXTRA = {
    "gacnst": "\t-WithBuildingPlacedOverlay:\n\tWithBuildingPlacedAnimation:\n",
    "nacnst": "\t-WithIdleOverlay@normal:\n",
    "gaweap": "\t-WithIdleOverlay@air-open:\n\t-WithIdleOverlay@air-inside:\n",
    "naweap": "\t-WithIdleOverlay@air-open:\n\t-WithIdleOverlay@air-inside:\n",
    "gaairc": "\t-WithIdleOverlay@mid:\n",
    "nahand": "\tWithIdleOverlay@flag:\n\t\tSequence: idle-flag\n",
    "natech": "\tWithIdleOverlay@lights:\n\t\tSequence: idle-lights\n",
}

# Soviet-side footprints -> the Allied ones the kit is drawn for (values from the resolved Allied rules).
FOOTPRINT = {
    "napowr": "\tBuilding:\n\t\tDimensions: 2,2\n\t\tFootprint: xx xx\n"
              "\tHitShape:\n\t\tTopLeft: -1024, -1024\n\t\tBottomRight: 1024, 1024\n",
    "nahand": "\tBuilding:\n\t\tDimensions: 3,2\n\t\tFootprint: xxx xxx\n"
              "\tHitShape:\n\t\tTopLeft: -1536, -1024\n\t\tBottomRight: 1536, 1024\n"
              "\tRallyPoint:\n\t\tPath: 2,3\n"
              "\tExit@0_2:\n\t\tSpawnOffset: -900,220,0\n\t\tExitCell: 0, 2\n"
              "\tExit@0_n1:\n\t\tSpawnOffset: 170,-810,0\n\t\tExitCell: 0, -1\n"
              "\tExit@2_2:\n\t\tSpawnOffset: -170,810,0\n\t\tExitCell: 2, 2\n"
              "\tExit@2_n1:\n\t\tSpawnOffset: 900,-220,0\n\t\tExitCell: 2, -1\n"
              + "".join(f"\t-Exit@{e}:\n" for e in ["1_2", "1_n1", "2_0", "2_1", "n1_0", "n1_1", "n1_2", "n1_n1"]),
    "nadept": "\tBuilding:\n\t\tDimensions: 3,3\n\t\tFootprint: x== x== x==\n"
              "\tHitShape:\n\t\tTopLeft: -1536, -1536\n\t\tBottomRight: 1536, 1536\n",
    "natech": "\tBuilding:\n\t\tDimensions: 3,2\n\t\tFootprint: xx xx xx\n"
              "\tHitShape:\n\t\tTopLeft: -1536, -1024\n\t\tBottomRight: 1536, 1024\n",
}

# Not in the kit, so not in the standalone game (they stay in the classic add-on).
CUT = {
    "gaorep": "Ore Purifier: +25% ore income",
    "gagap": "Gap Generator: shroud over a 10-cell radius",
    "gaspysat": "Spy Satellite: reveals the whole map",
    "gaweat": "Weather Control: Allied-side damage superweapon (lightning storm, 15000-tick charge)",
    "nanrct": "Nuclear Reactor: +2000 power for 1000 credits (the Soviet side keeps the 150-power plant)",
    "napsis": "Psychic Sensor: detects cloaked units within 6 cells",
    "naclon": "Cloning Vats: a free copy of every infantry unit produced",
    "namisl": "Nuclear Missile Silo: Soviet-side damage superweapon (15000-tick charge)",
}

TEXT = {
    "gacsph": ("Tooltip", "ChronoshiftPower@chronoshift", "sw1"),
    "nairon": ("Tooltip", "GrantExternalConditionPower@IRONCURTAIN", "sw2"),
}


def build() -> str:
    out = ["# GENERATED by tools/standalone-kit-rules.py: the base kit in the standalone game's rules. Standalone only.\n\n"]
    out.append("^Palettes:\n\tPaletteFromFile@kitbase:\n\t\tName: kitbase\n\t\tFilename: ra2|standalone/base/kitbase.pal\n"
               "\t\tShadowIndex: 1\n\tPlayerColorPalette@kitbase:\n\t\tBasePalette: kitbase\n\t\tBaseName: kitplayer\n"
               "\t\tRemapIndex: " + ", ".join(str(i) for i in range(16, 32)) + "\n\n")
    for actor, role in ROLE.items():
        block = [f"{actor}:\n\tRenderSprites:\n\t\tImage: {role}-china\n\t\tPlayerPalette: kitplayer\n\t\tFactionImages:\n"]
        block += [f"\t\t\t{f}: {role}-{f}\n" for f in FACTIONS]
        block.append(EXTRA.get(actor, ""))
        block.append(FOOTPRINT.get(actor, ""))
        if actor in TEXT:
            tip, power, key = TEXT[actor]
            block.append(f"\t{tip}:\n\t\tName: standalone-{key}-name\n\tBuildable:\n\t\tDescription: standalone-{key}-description\n"
                         f"\t{power}:\n\t\tName: standalone-{key}-power-name\n\t\tDescription: standalone-{key}-power-description\n")
        out.append("".join(block) + "\n")
    out.append("# Not part of the kit: out of the modern rosters in the standalone game (classic keeps them).\n")
    for actor, role in CUT.items():
        out.append(f"{actor}: # {role}\n\tBuildable:\n\t\tPrerequisites: ~disabled\n\n")
    text = "".join(out).rstrip("\n") + "\n"
    # HitShape's rectangle corners live under its Type (the shape), not on the trait itself
    text = re.sub(r"\tHitShape:\n\t\tTopLeft: ([^\n]+)\n\t\tBottomRight: ([^\n]+)\n",
                  r"\tHitShape:\n\t\tType: Rectangle\n\t\t\tLocalYaw: -128\n\t\t\tTopLeft: \1\n\t\t\tBottomRight: \2\n", text)
    return text


def main():
    OUT.write_text(build(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ROLE)} buildings on the kit, {len(FOOTPRINT)} footprints moved, "
          f"{len(CUT)} cut")


if __name__ == "__main__":
    main()
