#!/usr/bin/env python3
"""Project-drawn UI and world art for the standalone game (Phase 2): everything here is generated by code.

  shroud     shroud + fog edge sheets for ShroudRenderer (UseExtendedIndex, 48 masks)
  all        every target below

Outputs go to mods/rtsai/standalone/art/ and are referenced with explicit `ra2|standalone/art/...` paths from the
standalone-only overlay files (standalone/sequences.yaml, standalone/rules.yaml), so the classic add-on keeps the
original look with the player's own files.

usage: python tools/standalone-art.py shroud
"""
from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import numpy as np
from PIL import Image
from PIL.PngImagePlugin import PngInfo

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mods" / "rtsai"
ART = MOD / "standalone" / "art"


def sheet_png(frames: list[np.ndarray], path: Path, cols: int = 8):
    """RGBA frames (h, w, 4) of equal size -> PNG sheet with OpenRA PngSheet metadata."""
    h, w = frames[0].shape[:2]
    rows = math.ceil(len(frames) / cols)
    im = np.zeros((rows * h, cols * w, 4), np.uint8)
    for i, f in enumerate(frames):
        y, x = (i // cols) * h, (i % cols) * w
        im[y:y + h, x:x + w] = f
    meta = PngInfo()
    meta.add_text("FrameSize", f"{w},{h}")
    meta.add_text("FrameAmount", str(len(frames)))
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(im, "RGBA").save(path, pnginfo=meta, optimize=True)


# ------------------------------------------------------------------------------------------------ shroud and fog
def shroud_index() -> list[int]:
    text = (MOD / "rules" / "palettes.yaml").read_text(encoding="utf-8")
    m = re.search(r"ShroudRenderer:\n\t\tIndex: ([0-9, ]+)", text)
    return [int(x) for x in m[1].split(",")]


def shroud_frames(max_alpha: float, falloff: float = 0.9) -> list[np.ndarray]:
    """One frame per Index entry. A cell is a 60x30 diamond; s runs along cell +x (screen down-right), t along cell
    +y (screen down-left). Edge bits: 0x10 top (t=0), 0x20 right (s=1), 0x40 bottom (t=1), 0x80 left (s=0);
    corner bits (only when neither adjacent side is set): 0x01 TL (0,0), 0x02 TR (1,0), 0x04 BR (1,1), 0x08 BL (0,1).
    Darkness eases from the hidden side across `falloff` of the cell; a fully hidden cell (240) is solid."""
    W, H = 60, 30   # one cell; pixel centres are never on a diamond edge, so neighbours partition pixels exactly
    ys, xs = np.mgrid[0:H, 0:W].astype(np.float64)
    px = xs + 0.5 - W / 2
    py = ys + 0.5 - H / 2
    s = (px / 30 + py / 15 + 1) / 2
    t = (py / 15 + 1 - px / 30) / 2
    inside = (s >= 0) & (s < 1) & (t >= 0) & (t < 1)

    def ease(d):
        x = np.clip(1 - d / falloff, 0, 1)
        return x * x * (3 - 2 * x)

    sides = {0x10: t, 0x20: 1 - s, 0x40: 1 - t, 0x80: s}
    corners = {0x01: np.hypot(s, t), 0x02: np.hypot(1 - s, t), 0x04: np.hypot(1 - s, 1 - t), 0x08: np.hypot(s, 1 - t)}
    frames = []
    for v in shroud_index():
        if v & 0xF0 == 0xF0:
            alpha = np.where(inside, 1.0, 0.0)
        else:
            keep = np.ones_like(s)
            for bit, d in sides.items():
                if v & bit:
                    keep *= 1 - ease(np.clip(d, 0, None))
            for bit, d in corners.items():
                if v & bit:
                    keep *= 1 - ease(d / 1.15)
            alpha = np.where(inside, 1 - keep, 0.0)
        f = np.zeros((H, W, 4), np.uint8)
        f[..., 3] = np.round(np.clip(alpha, 0, 1) * max_alpha * 255).astype(np.uint8)
        frames.append(f)
    return frames


def build_shroud():
    sheet_png(shroud_frames(1.0), ART / "shroud.png")
    sheet_png(shroud_frames(0.55), ART / "fog.png")
    print(f"shroud: {len(shroud_index())} masks -> {ART / 'shroud.png'}, {ART / 'fog.png'}")


TARGETS = {"shroud": build_shroud}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("target", choices=[*TARGETS, "all"])
    a = ap.parse_args()
    for name, fn in TARGETS.items():
        if a.target in (name, "all"):
            fn()


if __name__ == "__main__":
    main()
