#!/usr/bin/env python3
"""Project-drawn UI and world art for the standalone game (Phase 2): everything here is generated by code.

  shroud     shroud + fog edge sheets for ShroudRenderer (UseExtendedIndex, 48 masks)
  all        every target below

Both standalone modes use project-made art. RA2 outputs go to mods/rtsai/standalone/art/;
Classic square-grid masks go to mods/rtsai-topdown/art/, with independent explicit sequence paths.

usage: python tools/standalone-art.py shroud
"""
from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import numpy as np
from PIL import Image
from PIL.PngImagePlugin import PngInfo

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mods" / "rtsai"
ART = MOD / "standalone" / "art"


def sheet_png(frames: list[np.ndarray], path: Path, cols: int = 8):
    """RGBA frames (h, w, 4) of equal size -> PNG sheet with OpenRA PngSheet metadata."""
    h, w = frames[0].shape[:2]
    rows = math.ceil(len(frames) / cols)
    im = np.zeros((rows * h, cols * w, 4), np.uint8)
    for i, f in enumerate(frames):
        y, x = (i // cols) * h, (i % cols) * w
        im[y:y + h, x:x + w] = f
    meta = PngInfo()
    meta.add_text("FrameSize", f"{w},{h}")
    meta.add_text("FrameAmount", str(len(frames)))
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.fromarray(im, "RGBA").save(path, pnginfo=meta, optimize=True)


# ------------------------------------------------------------------------------------------------ shroud and fog
def shroud_index() -> list[int]:
    text = (MOD / "rules" / "palettes.yaml").read_text(encoding="utf-8")
    m = re.search(r"ShroudRenderer:\n\t\tIndex: ([0-9, ]+)", text)
    return [int(x) for x in m[1].split(",")]


def shroud_frames(max_alpha: float, falloff: float = 0.9, rectangular: bool = False) -> list[np.ndarray]:
    """One frame per Index entry. A cell is a 60x30 diamond; s runs along cell +x (screen down-right), t along cell
    +y (screen down-left). Edge bits: 0x10 top (t=0), 0x20 right (s=1), 0x40 bottom (t=1), 0x80 left (s=0);
    corner bits (only when neither adjacent side is set): 0x01 TL (0,0), 0x02 TR (1,0), 0x04 BR (1,1), 0x08 BL (0,1).
    Darkness eases from the hidden side across `falloff` of the cell; a fully hidden cell (240) is solid."""
    W, H = (32, 32) if rectangular else (60, 30)
    ys, xs = np.mgrid[0:H, 0:W].astype(np.float64)
    px = xs + 0.5 - W / 2
    py = ys + 0.5 - H / 2
    s = (xs + 0.5) / W if rectangular else (px / 30 + py / 15 + 1) / 2
    t = (ys + 0.5) / H if rectangular else (py / 15 + 1 - px / 30) / 2
    inside = (s >= 0) & (s < 1) & (t >= 0) & (t < 1)

    def ease(d):
        x = np.clip(1 - d / falloff, 0, 1)
        return x * x * (3 - 2 * x)

    sides = {0x10: t, 0x20: 1 - s, 0x40: 1 - t, 0x80: s}
    corners = {0x01: np.hypot(s, t), 0x02: np.hypot(1 - s, t), 0x04: np.hypot(1 - s, 1 - t), 0x08: np.hypot(s, 1 - t)}
    frames = []
    for v in shroud_index():
        if v & 0xF0 == 0xF0:
            alpha = np.where(inside, 1.0, 0.0)
        else:
            keep = np.ones_like(s)
            for bit, d in sides.items():
                if v & bit:
                    keep *= 1 - ease(np.clip(d, 0, None))
            for bit, d in corners.items():
                if v & bit:
                    keep *= 1 - ease(d / 1.15)
            alpha = np.where(inside, 1 - keep, 0.0)
        f = np.zeros((H, W, 4), np.uint8)
        f[..., 3] = np.round(np.clip(alpha, 0, 1) * max_alpha * 255).astype(np.uint8)
        frames.append(f)
    return frames


def build_shroud():
    sheet_png(shroud_frames(1.0), ART / "shroud.png")
    sheet_png(shroud_frames(0.55), ART / "fog.png")
    print(f"shroud: {len(shroud_index())} masks -> {ART / 'shroud.png'}, {ART / 'fog.png'}")


def build_classic_shroud():
    """Square-grid masks; preserve the independent RA2 diamond masks."""
    import hashlib
    import json
    output = ROOT / "mods/rtsai-topdown/art"
    records = []
    for name, alpha in (("shroud.png", 1.0), ("fog.png", 0.55)):
        path = output / name
        sheet_png(shroud_frames(alpha, rectangular=True), path)
        records.append({"file": name, "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                        "origin": "Project-generated square-grid alpha masks; no external source artwork.",
                        "generator": "python tools/standalone-art.py shroud-classic", "license": "GPL-3.0-or-later",
                        "frame_size": [32, 32], "frames": len(shroud_index())})
    (output / "PROVENANCE.json").write_text(json.dumps({"assets": records}, indent=2) + "\n", encoding="utf-8")
    print("Classic square shroud and fog masks generated with provenance.")


# ------------------------------------------------------------------------------------------------ cursors
CUR = 32            # frame size (px); drawn at 4x and downsampled
SS = 4
INK, WHITE = (18, 22, 28, 255), (244, 247, 250, 255)
COL = {"move": (96, 226, 126), "attack": (244, 72, 60), "guard": (246, 196, 70), "deploy": (86, 206, 246),
       "enter": (102, 156, 255), "sell": (250, 206, 74), "repair": (150, 230, 96), "power": (196, 120, 255),
       "nuke": (255, 128, 48), "heal": (110, 236, 140), "blocked": (236, 56, 56), "neutral": (230, 236, 242)}


def _canvas():
    from PIL import ImageDraw
    im = Image.new("RGBA", (CUR * SS, CUR * SS), (0, 0, 0, 0))
    return im, ImageDraw.Draw(im)


def _done(im):
    return np.array(im.resize((CUR, CUR), Image.LANCZOS))


def _poly(d, pts, fill, w=2.2):
    s = SS
    p = [(x * s, y * s) for x, y in pts]
    d.polygon(p, fill=fill)
    d.line(p + [p[0]], fill=INK, width=int(w * s), joint="curve")


def _ring(d, cx, cy, r, color, w=2.0):
    s = SS
    d.ellipse([(cx - r) * s, (cy - r) * s, (cx + r) * s, (cy + r) * s], outline=INK, width=int((w + 1.6) * s))
    d.ellipse([(cx - r) * s, (cy - r) * s, (cx + r) * s, (cy + r) * s], outline=color, width=int(w * s))


def _line(d, a, b, color, w=2.0):
    s = SS
    d.line([(a[0] * s, a[1] * s), (b[0] * s, b[1] * s)], fill=INK, width=int((w + 1.6) * s))
    d.line([(a[0] * s, a[1] * s), (b[0] * s, b[1] * s)], fill=color, width=int(w * s))


def cur_arrow(phase=0.0, color=WHITE):
    im, d = _canvas()
    _poly(d, [(1.5, 1.5), (1.5, 21), (6.5, 16.5), (10, 24.5), (13.5, 23), (10.2, 15.2), (17, 15)], color)
    return _done(im)


def cur_scroll(angle, blocked=False):
    im, d = _canvas()
    a = math.radians(angle)
    c, s_ = math.cos(a), math.sin(a)
    tri = [(14, 0), (-2, -9), (2, 0), (-2, 9)]
    pts = [(16 + x * c - y * s_, 16 + x * s_ + y * c) for x, y in tri]
    _poly(d, pts, (*COL["blocked"], 255) if blocked else WHITE)
    return _done(im)


def cur_brackets(phase):
    im, d = _canvas()
    k = 3 + 2.5 * (0.5 + 0.5 * math.cos(phase * 2 * math.pi))
    for sx in (-1, 1):
        for sy in (-1, 1):
            cx, cy = 16 + sx * (16 - k - 2), 16 + sy * (16 - k - 2)
            _line(d, (cx, cy), (cx - sx * 7, cy), WHITE)
            _line(d, (cx, cy), (cx, cy - sy * 7), WHITE)
    return _done(im)


def cur_chevrons(phase, color):
    im, d = _canvas()
    off = 3 * (1 - phase)
    for ang in (0, 90, 180, 270):
        a = math.radians(ang)
        c, s_ = math.cos(a), math.sin(a)
        pts = [(-12 - off, -5), (-6 - off, 0), (-12 - off, 5)]
        pts = [(16 + x * c - y * s_, 16 + x * s_ + y * c) for x, y in pts]
        _line(d, pts[0], pts[1], (*color, 255))
        _line(d, pts[1], pts[2], (*color, 255))
    _ring(d, 16, 16, 1.6, (*color, 255), 1.5)
    return _done(im)


def cur_crosshair(phase, color):
    im, d = _canvas()
    r = 9 + 1.5 * math.sin(phase * 2 * math.pi)
    _ring(d, 16, 16, r, (*color, 255))
    for ang in (0, 90, 180, 270):
        a = math.radians(ang + 45 * phase)
        _line(d, (16 + math.cos(a) * (r - 4), 16 + math.sin(a) * (r - 4)),
              (16 + math.cos(a) * (r + 5), 16 + math.sin(a) * (r + 5)), (*color, 255))
    return _done(im)


def cur_shield(phase, color):
    im, d = _canvas()
    g = 1 + 0.08 * math.sin(phase * 2 * math.pi)
    pts = [(16 + x * g, 16 + y * g) for x, y in [(0, -11), (9, -7), (8, 3), (0, 11), (-8, 3), (-9, -7)]]
    _poly(d, pts, (*color, 255))
    return _done(im)


def cur_expand(phase, color):
    im, d = _canvas()
    k = 4 + 4 * phase
    for sx in (-1, 1):
        for sy in (-1, 1):
            tip = (16 + sx * (6 + k), 16 + sy * (6 + k))
            _line(d, (16 + sx * 3, 16 + sy * 3), tip, (*color, 255))
            _line(d, tip, (tip[0] - sx * 5, tip[1]), (*color, 255))
            _line(d, tip, (tip[0], tip[1] - sy * 5), (*color, 255))
    return _done(im)


def cur_enter(phase, color):
    im, d = _canvas()
    s = SS
    d.rectangle([7 * s, 13 * s, 25 * s, 27 * s], outline=INK, width=int(3.4 * s))
    d.rectangle([7 * s, 13 * s, 25 * s, 27 * s], outline=(*color, 255), width=int(2 * s))
    y = 2 + 6 * phase
    _poly(d, [(16, y + 10), (10, y + 3), (14, y + 3), (14, y - 2), (18, y - 2), (18, y + 3), (22, y + 3)], (*color, 255), 1.6)
    return _done(im)


def cur_coin(phase, color):
    im, d = _canvas()
    s = SS
    wscale = abs(math.cos(phase * math.pi))
    rx = max(1.5, 9 * wscale)
    d.ellipse([(16 - rx) * s, 7 * s, (16 + rx) * s, 25 * s], fill=(*color, 255), outline=INK, width=int(1.8 * s))
    if wscale > 0.45:
        _line(d, (16, 10), (16, 22), INK, 1.6)
        _line(d, (16 - rx * 0.4, 13), (16 + rx * 0.4, 13), INK, 1.6)
        _line(d, (16 - rx * 0.4, 19), (16 + rx * 0.4, 19), INK, 1.6)
    return _done(im)


def cur_wrench(phase, color):
    im, d = _canvas()
    a = math.radians(-30 + 60 * math.sin(phase * 2 * math.pi))
    c, s_ = math.cos(a), math.sin(a)

    def rot(x, y):
        return 16 + x * c - y * s_, 16 + x * s_ + y * c
    _line(d, rot(-9, 9), rot(5, -5), (*color, 255), 3.2)
    _ring(d, *rot(7, -7), 4.2, (*color, 255), 2.2)
    return _done(im)


def cur_flag(phase, color):
    im, d = _canvas()
    _line(d, (10, 27), (10, 4), WHITE, 1.8)
    pts = [(10.5, 5)] + [(10.5 + i * 1.6, 5 + 1.6 * math.sin(phase * 2 * math.pi + i * 0.8)) for i in range(1, 9)]
    pts += [(10.5 + i * 1.6, 13 + 1.6 * math.sin(phase * 2 * math.pi + i * 0.8)) for i in range(8, 0, -1)] + [(10.5, 13)]
    _poly(d, pts, (*color, 255), 1.6)
    return _done(im)


def cur_power(phase, color, glyph="ring"):
    im, d = _canvas()
    for i in range(2):
        r = 4 + ((phase + i * 0.5) % 1.0) * 10
        _ring(d, 16, 16, r, (*color, int(255 * (1 - ((phase + i * 0.5) % 1.0) * 0.6))), 1.6)
    s = SS
    if glyph == "cross":
        _line(d, (16, 11), (16, 21), WHITE, 2.4)
        _line(d, (11, 16), (21, 16), WHITE, 2.4)
    elif glyph == "bolt":
        _poly(d, [(17, 8), (11, 17), (15.5, 17), (14, 24), (21, 14), (16.5, 14)], (*color, 255), 1.4)
    elif glyph == "drop":
        d.pieslice([10 * s, 9 * s, 22 * s, 21 * s], 180, 360, fill=WHITE, outline=INK, width=int(1.4 * s))
        _line(d, (11, 15), (16, 23), WHITE, 1.2)
        _line(d, (21, 15), (16, 23), WHITE, 1.2)
    elif glyph == "bomb":
        d.ellipse([11 * s, 12 * s, 21 * s, 22 * s], fill=INK)
        _line(d, (19, 13), (23, 9), (*color, 255), 1.6)
    else:
        d.ellipse([14 * s, 14 * s, 18 * s, 18 * s], fill=(*color, 255), outline=INK, width=int(1 * s))
    return _done(im)


def cur_blocked():
    im, d = _canvas()
    _ring(d, 16, 16, 10, (*COL["blocked"], 255), 2.6)
    _line(d, (9, 23), (23, 9), (*COL["blocked"], 255), 2.6)
    return _done(im)


SCROLL_DIRS = {"t": -90, "tr": -45, "r": 0, "br": 45, "b": 90, "bl": 135, "l": 180, "tl": -135}


def cursor_frames(name: str, n: int):
    """Our drawing for an engine cursor name, as n animation frames."""
    ph = [i / max(1, n) for i in range(n)]
    base = name.replace("-minimap", "").replace("2", "")
    if name in ("default", "default-minimap"):
        return [cur_arrow()]
    if base.endswith("-blocked") or base in ("generic-blocked", "drop-blocked", "water-move-blocked", "attack-blocked"):
        if base.startswith("scroll-") or base.startswith("joystick-"):
            return [cur_scroll(SCROLL_DIRS[base.split("-")[1]], True)]
        return [cur_blocked()] * n
    if base.startswith("scroll-"):
        return [cur_scroll(SCROLL_DIRS[base.split("-")[1]])]
    if base.startswith("scrollclick") or base.startswith("joystick"):
        parts = base.split("-")
        return [cur_scroll(SCROLL_DIRS[parts[1]]) if len(parts) > 1 and parts[1] in SCROLL_DIRS else cur_power(0, COL["neutral"])]
    table = {
        "select": lambda p: cur_brackets(p),
        "move": lambda p: cur_chevrons(p, COL["move"]), "move-rough": lambda p: cur_chevrons(p, COL["move"]),
        "water-move": lambda p: cur_chevrons(p, COL["deploy"]), "ability": lambda p: cur_chevrons(p, COL["deploy"]),
        "attack": lambda p: cur_crosshair(p, COL["attack"]), "attackoutsiderange": lambda p: cur_crosshair(p, COL["guard"]),
        "harvest": lambda p: cur_crosshair(p, COL["sell"]), "c4": lambda p: cur_power(p, COL["attack"], "bomb"),
        "attackmove": lambda p: cur_crosshair(p, COL["nuke"]), "assaultmove": lambda p: cur_crosshair(p, COL["nuke"]),
        "guard": lambda p: cur_shield(p, COL["guard"]), "looped-patrol": lambda p: cur_shield(p, COL["move"]),
        "deploy": lambda p: cur_expand(p, COL["deploy"]), "dsol-deploy": lambda p: cur_expand(p, COL["deploy"]),
        "undeploy": lambda p: cur_expand(1 - p, COL["deploy"]), "undeploy-silver": lambda p: cur_expand(1 - p, COL["neutral"]),
        "deploy-sandbags": lambda p: cur_expand(p, COL["guard"]),
        "enter": lambda p: cur_enter(p, COL["enter"]), "capture": lambda p: cur_enter(p, COL["guard"]),
        "sell": lambda p: cur_coin(p, COL["sell"]), "goldwrench": lambda p: cur_wrench(p, COL["sell"]),
        "repair": lambda p: cur_wrench(p, COL["repair"]), "waypoint": lambda p: cur_flag(p, COL["move"]),
        "rallypoint": lambda p: cur_flag(p, COL["guard"]), "beacon-mouseover": lambda p: cur_power(p, COL["guard"]),
        "heal": lambda p: cur_power(p, COL["heal"], "cross"), "nuke": lambda p: cur_power(p, COL["nuke"], "bomb"),
        "detonate": lambda p: cur_power(p, COL["attack"], "bomb"), "bomb": lambda p: cur_power(p, COL["attack"], "bomb"),
        "remove-bomb": lambda p: cur_power(p, COL["move"], "bomb"), "weatherstorm": lambda p: cur_power(p, COL["deploy"], "bolt"),
        "praradrop": lambda p: cur_power(p, COL["neutral"], "drop"), "powerdown": lambda p: cur_power(p, COL["guard"], "bolt"),
    }
    fn = table.get(base) or table.get(name) or (lambda p: cur_power(p, COL["power"]))
    return [fn(p) for p in ph]


def build_cursors():
    """New cursor sheet + standalone cursors.yaml with the same sequence names as the stock one."""
    src = (MOD / "cursors.yaml").read_text(encoding="utf-8").replace("\r\n", "\n")
    names = []   # (name, length, has_xy)
    for m in re.finditer(r"^\t\t(\S+):[^\n]*\n((?:\t\t\t.*\n?)*)", src, re.M):   # a name may carry a comment
        body = m[2]
        ln = re.search(r"Length: (\S+)", body)
        names.append((m[1], int(ln[1]) if ln and ln[1] != "*" else 1, "X:" in body))
    seen, frames, yaml = set(), [], ["# GENERATED by tools/standalone-art.py: the standalone cursor set, drawn in code.\n"
                                     "# Same sequence names as the classic cursors.yaml; frame layout is our own.\n\n"
                                     "Cursors:\n\tra2|standalone/art/cursors.png: mouse\n"]
    for name, n, has_xy in names:
        if name in seen:
            continue
        seen.add(name)
        f = cursor_frames(name, n)
        start = len(frames)
        frames += f
        yaml.append(f"\t\t{name}:\n\t\t\tStart: {start}\n" + (f"\t\t\tLength: {len(f)}\n" if len(f) > 1 else ""))
        if name in ("default", "default-minimap"):
            yaml.append(f"\t\t\tX: {-(CUR // 2) + 1}\n\t\t\tY: {-(CUR // 2) + 1}\n")
    sheet_png(frames, ART / "cursors.png", cols=16)
    (MOD / "standalone" / "cursors.yaml").write_text("".join(yaml), encoding="utf-8", newline="\n")
    # The rally point marker: the flag and a pulsing ground ring (the stock ones were frames of the cursor sheet).
    flag = [cur_flag(i / 10, COL["guard"]) for i in range(10)]
    circles = []
    for i in range(10):
        im, d = _canvas()
        s = SS
        r = 5 + 9 * (i / 10)
        d.ellipse([(16 - r) * s, (16 - r / 2) * s, (16 + r) * s, (16 + r / 2) * s], outline=(*COL["guard"], int(255 * (1 - i / 12))),
                  width=int(1.6 * s))
        circles.append(_done(im))
    sheet_png(flag, ART / "rallypoint-flag.png", cols=10)
    sheet_png(circles, ART / "rallypoint-circles.png", cols=10)
    print(f"cursors: {len(seen)} sequences, {len(frames)} frames -> {ART / 'cursors.png'}")


# ------------------------------------------------------------------------------------------------ palettes
def general_palette() -> bytes:
    """A project palette for the remaining indexed art: 0 transparent, 1 shadow, 2-15 greys, 16-31 the player-colour
    remap ramp, 32-255 an HSV lattice (7 values x 4 saturations x 8 hues). 6-bit VGA values like every .pal."""
    import colorsys
    pal = [(0, 0, 0), (0, 0, 0)] + [(int(255 * i / 13),) * 3 for i in range(14)]
    for i in range(16):
        t = i / 15
        pal.append((int(255 * (1 - 0.8 * t)), int(48 * (1 - t)), int(40 * (1 - t))))
    for v in range(7):
        for s_ in range(4):
            for h in range(8):
                r, g, b = colorsys.hsv_to_rgb(h / 8, 0.25 + 0.25 * s_, 0.3 + 0.7 * v / 6)
                pal.append((int(r * 255), int(g * 255), int(b * 255)))
    assert len(pal) == 256
    return bytes(c >> 2 for rgb in pal for c in rgb)


def build_palettes():
    out = MOD / "standalone" / "palettes"
    out.mkdir(parents=True, exist_ok=True)
    (out / "general.pal").write_bytes(general_palette())
    print(f"palettes: {out / 'general.pal'}")


# ------------------------------------------------------------------------------------------------ orphan bits
# Replacements for the 20 files the mod inherited from the upstream OpenRA RA2 mod without a provenance record.
# Shared by the standalone game and the classic add-on (both load these instead of the originals).
BITS = MOD / "bits"


def region_sheet(frames, path: Path, offsets=None, palette=None):
    """Frames of any size -> one PNG with Frame[i] regions (and offsets). RGBA, or indexed with `palette`."""
    width = max(64, sum(f.shape[1] for f in frames[:16]))
    x = y = rowh = 0
    pos = []
    for f in frames:
        h, w = f.shape[:2]
        if x + w > width:
            x, y, rowh = 0, y + rowh, 0
        pos.append((x, y))
        x, rowh = x + w, max(rowh, h)
    H = y + rowh
    meta = PngInfo()
    if palette is None:
        im = np.zeros((H, width, 4), np.uint8)
    else:
        im = np.zeros((H, width), np.uint8)
    for i, (f, (px, py)) in enumerate(zip(frames, pos)):
        h, w = f.shape[:2]
        im[py:py + h, px:px + w] = f
        ox, oy = offsets[i] if offsets else (0, 0)
        meta.add_text(f"Frame[{i}]", f"{px},{py},{w},{h};{ox},{oy}")
    path.parent.mkdir(parents=True, exist_ok=True)
    if palette is None:
        Image.fromarray(im, "RGBA").save(path, pnginfo=meta, optimize=True)
    else:
        p = Image.fromarray(im, "P")
        p.putpalette(palette)
        p.save(path, pnginfo=meta, optimize=True, transparency=0)


def draw(size, fn, ss=4):
    from PIL import ImageDraw
    im = Image.new("RGBA", (size[0] * ss, size[1] * ss), (0, 0, 0, 0))
    fn(ImageDraw.Draw(im), ss)
    return np.array(im.resize(size, Image.LANCZOS))


def pip(color, w=5, h=7, empty=False):
    def f(d, s):
        d.rectangle([0, 0, w * s - 1, h * s - 1], fill=(14, 18, 22, 255))
        if not empty:
            d.rectangle([s, s, (w - 1) * s - 1, (h - 1) * s - 1], fill=(*color, 255))
    return draw((w, h), f)


def digit(n):
    from PIL import ImageFont
    font = ImageFont.load_default()

    def f(d, s):
        d.rectangle([0, 0, 8 * s - 1, 9 * s - 1], fill=(14, 18, 22, 230))
        d.text((1.5 * s, -0.5 * s), str(n), fill=(240, 240, 240, 255), font=font.font_variant(size=9 * s) if hasattr(font, "font_variant") else font)
    return draw((8, 9), f)


def build_bits():
    pc = {"empty": None, "green": (90, 220, 90), "yellow": (240, 210, 70), "gray": (150, 150, 150), "red": (230, 70, 60),
          "blue": (80, 150, 250)}
    frames = []
    for name, c in pc.items():                                  # 0-5 building pips
        frames.append(pip(c or (0, 0, 0), 6, 8, empty=c is None))
    frames.append(draw((9, 9), lambda d, s: (d.rectangle([3 * s, 0, 6 * s - 1, 9 * s - 1], fill=(235, 60, 60, 255)),
                                              d.rectangle([0, 3 * s, 9 * s - 1, 6 * s - 1], fill=(235, 60, 60, 255)))))  # 6 medic
    frames.append(pip((0, 0, 0), 2, 2, empty=True))             # 7 unused
    frames += [digit(n) for n in range(10)]                     # 8-17 control group numbers
    for name, c in pc.items():                                  # 18-23 small pips (pips2)
        frames.append(pip(c or (0, 0, 0), 4, 6, empty=c is None))
    frames.append(pip((240, 210, 70), 4, 9))                    # 24 ammo
    frames.append(pip((0, 0, 0), 4, 9, empty=True))             # 25 ammo empty
    for i in range(12):                                         # 26-37 disguise (a pulsing mask)
        a = int(150 + 105 * math.sin(i / 12 * 2 * math.pi))

        def mask(d, s, a=a):
            d.ellipse([0, 0, 14 * s - 1, 9 * s - 1], fill=(30, 34, 40, 255))
            d.ellipse([2 * s, 2 * s, 6 * s, 6 * s], fill=(220, 220, 230, a))
            d.ellipse([8 * s, 2 * s, 12 * s, 6 * s], fill=(220, 220, 230, a))
        frames.append(draw((14, 9), mask))
    for n in (1, 2):                                            # 38 veteran, 39 elite: rank chevrons

        def chevrons(d, s, n=n):
            for k in range(n):
                y = (1 + 4 * k) * s
                d.polygon([(0, y), (5 * s, y + 3 * s), (10 * s, y), (10 * s, y + 2.5 * s), (5 * s, y + 5.5 * s),
                           (0, y + 2.5 * s)], fill=(250, 210, 80, 255), outline=(40, 30, 10, 255))
        frames.append(draw((10, 6 + 4 * n), chevrons))
    region_sheet(frames, BITS / "pips-rtsai.png")

    # build clock: shaded sector shrinking clockwise from 12 o'clock; white = unchanged under Multiply
    clock = []
    ys, xs = np.mgrid[0:48, 0:60].astype(float)
    ang = (np.degrees(np.arctan2(xs + 0.5 - 30, -(ys + 0.5 - 24))) + 360) % 360
    for i in range(55):
        f = np.full((48, 60, 4), 255, np.uint8)
        shaded = ang >= 360 * i / 55
        f[shaded, :3] = (96, 100, 110)
        clock.append(f)
    sheet_png(clock, BITS / "clock-rtsai.png", cols=11)

    # construction yard cameos (classic factions; the modern factions get the base kit's icons)
    for name, tint in (("acnsicon-rtsai", (70, 110, 170)), ("scnsicon-rtsai", (160, 70, 60))):
        def cy(d, s, tint=tint):
            d.rectangle([0, 0, 60 * s - 1, 48 * s - 1], fill=(26, 30, 36, 255))
            for k in range(48):
                c = tuple(int(v * (0.55 + 0.45 * k / 47)) for v in tint)
                d.line([(0, k * s), (60 * s, k * s)], fill=(*c, 255), width=s)
            d.polygon([(12 * s, 36 * s), (30 * s, 26 * s), (48 * s, 36 * s), (30 * s, 44 * s)], fill=(190, 196, 204, 255))
            d.polygon([(12 * s, 36 * s), (30 * s, 44 * s), (30 * s, 47 * s), (12 * s, 39 * s)], fill=(120, 126, 134, 255))
            d.polygon([(48 * s, 36 * s), (30 * s, 44 * s), (30 * s, 47 * s), (48 * s, 39 * s)], fill=(150, 156, 164, 255))
            d.line([(36 * s, 33 * s), (36 * s, 8 * s)], fill=(240, 200, 60, 255), width=2 * s)
            d.line([(36 * s, 8 * s), (16 * s, 14 * s)], fill=(240, 200, 60, 255), width=2 * s)
            d.line([(18 * s, 14 * s), (18 * s, 24 * s)], fill=(220, 220, 220, 255), width=s)
            d.rectangle([0, 0, 60 * s - 1, 48 * s - 1], outline=(10, 12, 16, 255), width=s)
        sheet_png([draw((60, 48), cy)], BITS / "cameos" / f"{name}.png", cols=1)

    # editor/lobby markers on the ground (diamond + glyph)
    def marker(glyph, color):
        def f(d, s):
            d.polygon([(24 * s, 1 * s), (47 * s, 12 * s), (24 * s, 23 * s), (1 * s, 12 * s)], outline=(*color, 255), width=2 * s)
            glyph(d, s, color)
        return draw((48, 24), f)

    def star(d, s, c):
        pts = []
        for k in range(10):
            r = (7 if k % 2 == 0 else 3) * s
            a = math.radians(-90 + k * 36)
            pts.append((24 * s + r * math.cos(a) * 1.4, 12 * s + r * math.sin(a)))
        d.polygon(pts, fill=(*c, 255))

    def flag(d, s, c):
        d.line([(20 * s, 19 * s), (20 * s, 4 * s)], fill=(*c, 255), width=2 * s)
        d.polygon([(21 * s, 4 * s), (31 * s, 7 * s), (21 * s, 10 * s)], fill=(*c, 255))

    def eye(d, s, c):
        d.ellipse([16 * s, 8 * s, 32 * s, 16 * s], outline=(*c, 255), width=2 * s)
        d.ellipse([22 * s, 10 * s, 26 * s, 14 * s], fill=(*c, 255))
    sheet_png([marker(star, (250, 210, 70))], BITS / "spawn-marker.png", cols=1)
    sheet_png([marker(flag, (90, 220, 120))], BITS / "waypoint-marker.png", cols=1)
    sheet_png([marker(eye, (110, 170, 255))], BITS / "camera-marker.png", cols=1)

    # air-dropped bomb, 32 facings (facing 0 = north, counter-clockwise like the engine's facings)
    bomb = []
    for i in range(32):
        a = math.radians(-i * 360 / 32)

        def f(d, s, a=a):
            cx, cy = 8 * s, 8 * s
            dx, dy = math.sin(a), -math.cos(a) * 0.5
            L = 6 * s
            p1 = (cx + dx * L, cy + dy * L)
            p2 = (cx - dx * L, cy - dy * L)
            d.line([p1, p2], fill=(60, 64, 58, 255), width=4 * s)
            d.ellipse([p1[0] - 2 * s, p1[1] - 2 * s, p1[0] + 2 * s, p1[1] + 2 * s], fill=(60, 64, 58, 255))
            d.line([p2, (p2[0] - dx * 2 * s, p2[1] - dy * 2 * s)], fill=(140, 140, 120, 255), width=3 * s)
        bomb.append(draw((16, 16), f))
    sheet_png(bomb, BITS / "bomb-rtsai.png", cols=8)

    # classic cursors that were upstream sheets: attack-move and undeploy (55x43 frames like the RA2 sheet)
    am = [np.pad(cur_crosshair(i / 9, COL["nuke"]), ((5, 6), (11, 12), (0, 0))) for i in range(9)]
    am.append(np.pad(cur_crosshair(0.0, (150, 150, 150)), ((5, 6), (11, 12), (0, 0))))
    sheet_png(am, BITS / "assaultmove-cursor.png", cols=10)
    ud = [np.pad(cur_expand(1 - i / 7, COL["deploy"]), ((5, 6), (11, 12), (0, 0))) for i in range(7)]
    sheet_png(ud, BITS / "undeploy-cursor.png", cols=7)

    # veterancy chevron over build icons, and the palette it is drawn with (PaletteFromPng reads this file's palette)
    pal = np.array(list(general_palette()), np.uint8).reshape(-1, 3).astype(int) * 4
    pal = np.clip(pal + pal // 64, 0, 255).astype(np.uint8)
    idx_gold = int(np.argmin(((pal[32:] - (240, 200, 70)) ** 2).sum(1))) + 32
    idx_dark = 3
    chev = np.zeros((10, 14), np.uint8)
    for k in range(3):
        for x in range(14):
            y = 2 + k * 3 + abs(x - 6.5) * 0.45
            yi = int(round(y))
            if 0 <= yi < 10:
                chev[yi, x] = idx_gold
                if yi + 1 < 10:
                    chev[yi + 1, x] = idx_dark
    region_sheet([chev], BITS / "cameos" / "cameo-chevron.png", palette=pal.ravel().tolist())

    # building depth ramp (DepthSprite): a formula, not art. 288x197, every row
    # 0 | 71 71 70 70 ... 1 1 0 0 1 1 ... 70 70 71 71 | 0  (palette index = depth step)
    row = np.zeros(288, np.uint8)
    for x in range(1, 287):
        k = (x - 1) // 2
        row[x] = 71 - k if k <= 71 else k - 71
    depth = np.tile(row, (197, 1))
    grey = np.array([[i, i, i] for i in range(256)], np.uint8).ravel().tolist()
    region_sheet([depth], BITS / "isodepth.png", palette=grey)
    print("bits: pips, clock, construction-yard cameos, markers, bomb, classic cursors, cameo chevron, isodepth")


# ------------------------------------------------------------------------------------------------ smudges, move flash
def _value_noise(shape, scale, rng):
    """Smooth 2D noise in [0, 1]: bilinear upsampling of a coarse random grid."""
    h, w = shape
    gh, gw = int(math.ceil(h / scale)) + 2, int(math.ceil(w / scale)) + 2
    g = rng.random((gh, gw))
    ys, xs = np.mgrid[0:h, 0:w] / scale
    y0, x0 = ys.astype(int), xs.astype(int)
    fy, fx = ys - y0, xs - x0
    fy, fx = fy * fy * (3 - 2 * fy), fx * fx * (3 - 2 * fx)
    a, b = g[y0, x0], g[y0, x0 + 1]
    c, d = g[y0 + 1, x0], g[y0 + 1, x0 + 1]
    return (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy


def _plane(size, ss):
    """Pixel grid -> isometric ground-plane distance units (1 = one cell edge = 30 px across, 15 px down)."""
    n = size * ss
    ys, xs = np.mgrid[0:n, 0:n].astype(float) / ss
    px, py = (xs - size / 2) / 30.0, (ys - size / 2) / 15.0     # screen -> plane: 2:1
    return px, py


def _down(rgba, ss):
    h, w = rgba.shape[0] // ss, rgba.shape[1] // ss
    r = rgba.reshape(h, ss, w, ss, 4).astype(float)
    a = r[..., 3:4].mean(axis=(1, 3))
    rgb = (r[..., :3] * r[..., 3:4]).mean(axis=(1, 3)) / np.maximum(a, 1e-6)
    return np.clip(np.concatenate([rgb, a], -1) + 0.5, 0, 255).astype(np.uint8)


def scorch(radius, seed, size=120, ss=3):
    """A soot blotch on the ground: dark, irregular, alpha-faded edges, a few charred streaks and specks."""
    rng = np.random.default_rng(seed)
    px, py = _plane(size, ss)
    r = np.hypot(px, py)
    ang = np.arctan2(py, px)
    edge = radius * (0.78 + 0.32 * _value_noise(r.shape, 9 * ss, rng))
    streaks = np.zeros_like(r)
    for a0 in rng.uniform(-math.pi, math.pi, 7):                    # radial soot streaks
        d = np.angle(np.exp(1j * (ang - a0)))
        streaks = np.maximum(streaks, np.exp(-(d / 0.12) ** 2) * (r < radius * rng.uniform(1.1, 1.45)))
    body = np.clip(1 - (r / edge) ** 2, 0, 1) ** 0.35
    a = np.clip(0.95 * body + 0.5 * streaks * (r > radius * 0.4), 0, 0.95)
    a *= 0.85 + 0.15 * _value_noise(r.shape, 3 * ss, rng)
    tone = 10 + 26 * _value_noise(r.shape, 4 * ss, rng)
    burnt = np.clip((r / edge - 0.55) / 0.45, 0, 1) * (r < edge)          # browner, scorched soil at the margin
    rgb = np.stack([tone * 1.1 + 40 * burnt, tone * 0.95 + 24 * burnt, tone * 0.8 + 10 * burnt], -1)
    specks = (_value_noise(r.shape, 1.5 * ss, rng) > 0.86) & (r < radius * 1.3)
    a = np.where(specks, np.maximum(a, 0.85), a)
    rgba = np.concatenate([rgb, (a * 255)[..., None]], -1)
    return _down(rgba, ss)


def crater(radius, seed, size=120, ss=3):
    """A shell crater: a bowl lit from the upper left (the game's light), a raised rim of thrown-up soil, loose
    clods outside it, soot at the bottom; fades into the ground at the edge."""
    rng = np.random.default_rng(seed)
    px, py = _plane(size, ss)
    n = _value_noise(px.shape, 7 * ss, rng)
    R = radius * (0.85 + 0.25 * n)
    r = np.hypot(px, py) / R
    h = np.where(r < 1, -(1 - r ** 2), 0) + 0.45 * np.exp(-((r - 1.0) / 0.22) ** 2)   # bowl + rim
    gy, gx = np.gradient(h * radius * 0.45)
    k = 30.0 * ss
    nz = 1.0 / np.sqrt(1 + (gx * k) ** 2 + (gy * k) ** 2)
    light = np.array([-0.6, -0.5, 0.62])
    light /= np.linalg.norm(light)
    shade = np.clip((-gx * k * light[0] - gy * k * light[1] + light[2]) * nz, 0, 1)
    soil = np.array([122, 94, 64], float)
    rgb = soil[None, None, :] * (0.25 + 1.05 * shade[..., None]) * (0.9 + 0.2 * n[..., None])
    soot = np.clip(1 - r / 0.55, 0, 1)
    rgb = rgb * (1 - 0.55 * soot[..., None])
    a = np.clip((1.38 - r) / 0.4, 0, 1)                              # opaque soil inside, fading past the rim
    a = a * a * (3 - 2 * a)
    clods = (_value_noise(px.shape, 1.6 * ss, rng) > 0.8) & (r > 0.95) & (r < 1.6)
    a = np.where(clods, 0.95, a) * 0.97
    rgb = np.where(clods[..., None], soil * 0.8, rgb)
    rgba = np.concatenate([rgb, (a * 255)[..., None]], -1)
    return _down(rgba, ss)


SMUDGE_SIZES = {"small": 0.6, "medium": 1.05, "large": 1.6}      # radius in cell edges
SMUDGES = {"scorches": ("sc", scorch, {"small": 6, "medium": 4, "large": 2}),
           "craters": ("cr", crater, {"small": 6, "medium": 4, "large": 2})}


def build_smudges():
    """Scorch marks and craters for SmudgeLayer: one sheet per smudge image, a frame per sequence (sc1..sc12,
    cr1..cr12, numbered across sizes like the stock files), plus standalone/smudge-sequences.yaml."""
    yaml = ["# GENERATED by tools/standalone-art.py smudges: scorch marks and craters drawn by code.\n\n"]
    for kind, (prefix, fn, counts) in SMUDGES.items():
        k = 1
        for size, count in counts.items():
            frames = [fn(SMUDGE_SIZES[size] * (1 + 0.08 * i), seed=hash((kind, size, i)) & 0xFFFF) for i in range(count)]
            name = f"{size}{kind}"
            sheet_png(frames, ART / "smudges" / f"{name}.png", cols=count)
            yaml.append(f"{name}:\n\tDefaults:\n\t\tFilename: ra2|standalone/art/smudges/{name}.png\n"
                        "\t\tOffset: 0, 0, 1\n\t\tZRamp: 1\n")
            for i in range(count):
                yaml.append(f"\t{prefix}{k}:\n\t\t-TilesetFilenames:\n\t\tStart: {i}\n")
                k += 1
            yaml.append("\n")
    (MOD / "standalone" / "smudge-sequences.yaml").write_text("".join(yaml).rstrip("\n") + "\n", encoding="utf-8",
                                                             newline="\n")
    print(f"smudges: {ART / 'smudges'} (12 scorches, 12 craters)")


def build_moveflash():
    """The move-order flash: an isometric ring that grows and fades (15 frames, 82x46 like the stock ring)."""
    frames = []
    for i in range(15):
        t = i / 14

        def ring(d, s, t=t):
            rx, ry = (10 + 28 * t) * s, (5 + 14 * t) * s
            cx, cy = 41 * s, 23 * s
            a = int(255 * (1 - t) ** 1.3)
            for k, (wd, col) in enumerate(((3.2, (20, 40, 46, a)), (1.8, (120, 230, 240, a)))):
                d.ellipse([cx - rx, cy - ry, cx + rx, cy + ry], outline=col, width=max(1, int(wd * s)))
        frames.append(draw((82, 46), ring))
    sheet_png(frames, ART / "moveflash.png", cols=15)
    print(f"move flash: {ART / 'moveflash.png'}")


TARGETS = {"shroud": build_shroud, "shroud-classic": build_classic_shroud, "cursors": build_cursors, "palettes": build_palettes, "bits": build_bits,
           "smudges": build_smudges, "moveflash": build_moveflash}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("target", choices=[*TARGETS, "all"])
    a = ap.parse_args()
    for name, fn in TARGETS.items():
        if a.target in (name, "all"):
            fn()


if __name__ == "__main__":
    main()
