#!/usr/bin/env python3
"""Neutral names for the standalone game: no Red Alert 2 coined unit or building name on screen.

The shared text (languages/rules/en.ftl, modern-factions/*-messages.ftl) keeps the stock names, which the classic
add-on shows with the player's own RA2 files. The standalone game loads mods/rtsai/standalone/names.ftl last; it
overrides every message whose text uses one of the stock phrases below, with the phrase replaced (Fluent: a later
file's message replaces an earlier one with the same id). `--check-standalone` fails on any stock name left in the
text of what the factions can field, so a new stock phrase shows up there first; add it to REPLACE and re-run.

    python tools/standalone-names.py           # writes mods/rtsai/standalone/names.ftl
    python tools/standalone-names.py --check   # exits 1 when names.ftl is stale
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mods" / "rtsai"
OUT = MOD / "standalone" / "names.ftl"

# Stock phrase -> neutral phrase, longest first (applied in this order).
REPLACE = [
    ("Airforce Command Headquarters", "Airfield"),
    ("returns to Airforce Command", "returns to the Airfield"),
    ("Airforce Command", "Airfield"),
    (" and removes Terror Drones (for a price)", " (for a price)"),
    ("Tesla Reactor", "Power Plant"),
    ("Chrono Miner", "Ore Harvester"),
    ("War Miner", "Armed Harvester"),
    ("Flak Track", "AA Carrier"),
    ("Battle Lab", "Tech Center"),
    ("War Factory", "Vehicle Factory"),
    ("Allied Wall", "Wall"),
    ("Soviet Wall", "Wall"),
]


def sources() -> list[Path]:
    """The shared Fluent files of the standalone manifest, in load order (standalone/ files excluded)."""
    text = (MOD / "mod.yaml").read_text(encoding="utf-8").replace("\r\n", "\n")
    block = re.search(r"(?ms)^FluentMessages:\n(.*?)(?=^\S|\Z)", text)[1]
    out = []
    for line in block.splitlines():
        ref = line.strip()
        if ref.startswith("ra2|") and not ref.startswith("ra2|standalone/"):
            out.append(MOD / ref[4:])
    return out


def messages(path: Path):
    """(id, full message text including continuation lines) for every top-level message of a Fluent file."""
    lines = path.read_text(encoding="utf-8").replace("\r\n", "\n").split("\n")
    i = 0
    while i < len(lines):
        m = re.match(r"^(-?[A-Za-z][\w-]*)\s*=", lines[i])
        if not m:
            i += 1
            continue
        j = i + 1
        while j < len(lines) and (lines[j].startswith((" ", "\t")) or (lines[j] == "" and j + 1 < len(lines)
                                                                       and lines[j + 1].startswith((" ", "\t")))):
            j += 1
        yield m[1], "\n".join(lines[i:j]).rstrip("\n")
        i = j


def build() -> str:
    latest = {}
    for src in sources():
        for mid, text in messages(src):
            latest[mid] = (text, src)
    out = ["# GENERATED by tools/standalone-names.py: neutral names for the standalone game. Overrides the shared\n"
           "# messages that use a Red Alert 2 coined name (the classic add-on keeps them). Do not edit by hand.\n\n"]
    n = 0
    for mid, (text, src) in latest.items():
        new = text
        for old, rep in REPLACE:
            new = new.replace(old, rep)
        if new != text:
            out.append(f"## from {src.relative_to(MOD).as_posix()}\n{new}\n\n")
            n += 1
    return "".join(out).rstrip("\n") + "\n", n


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text, n = build()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale: run tools/standalone-names.py")
        print(f"{OUT.relative_to(ROOT)} is up to date ({n} messages)")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {n} messages with neutral names")


if __name__ == "__main__":
    main()
