## Generated by tools/faction-loading-tips.py from OpenRA-AI/catalog/factions.json. Do not edit by hand.
## Catalog revision 2026-10-07.1, sha256 655dfe0dddfd. One tip per line, shown by RTSAILoadScreen.
## In-world perspectives in a fictional game conflict (see the catalog's narrative.framing).

loadscreen-faction-tips =
    China: The network is awake. What one unit sees, every unit sees.
    Türkiye on China: "Every Haitan pier is long enough for a carrier. Ask yourself why."
    Iran: Every pass guarded, every coast contested. Let the enemy choose a road.
    Saudi Arabia on Iran: "Their talk is of brotherhood. Their missile ranges grow every year."
    Türkiye: A bridge between continents must be guarded from both sides.
    Iran on Türkiye: "One foot in a distant alliance, the other on our border."
    Saudi Arabia: The corridor carries a nation's future. Hold it.
    Yemen on Saudi Arabia: "Wealth buys armor. It cannot buy consent."
    Yemen: We have little steel, so we bring patience. And speed.
    China on Yemen: "Every container they delay raises the price of bread somewhere far away."
    Israel: Nobody moves alone. The observer, the tank and the shield cover each other.
    Hezbollah on Israel: "They fly over our hills as if the sky belonged to them."
    Hezbollah: Simple rockets. Small wings. Fighters who know every ridge.
    Israel on Hezbollah: "An armed movement that decides when a whole country goes to war."
